/** All primary and foreign keys are integers; primary keys are generated by the database. */
export interface Customer {
  customer_id: number;
  customer_name: string;
  phone_number: string;
  line_id: string | null;
}

export interface Project {
  project_id: number;
  customer_id: number;
  description_project: string | null;
  status: string;
  base_cost: number;
  labor_cost: number;
  service_percent: number;
  final_cost: number;
  order_name: string;
}

export interface Employee {
  employee_id: number;
  employee_name: string;
  role: string;
  phone_number: string;
}

export interface WorkOn {
  employee_id: number;
  project_id: number;
}

export interface Appointment {
  appointment_id: number;
  project_id: number;
  customer_id: number;
  appointment_type: "installation" | "pickup" | "site_visit";
  location: string;
  appointment_datetime: string;
  status: string;
  reminder_status: "pending" | "send" | "failed";
  reminder_sent_at: string | null;
}

export interface JobMaterial {
  job_material_id: number;
  project_id: number;
  quantity: number;
  material_name: string;
  use_for: string | null;
  unit: string;
  unit_cost: number;
}

export interface Payment {
  payment_id: number;
  project_id: number;
  proof_of_payment: string | null;
  payment_date: string | null;
  amount: number;
}
